
name: GitHub Actions Demo
# which trigger or triggers [push, pull_request] to run 
on: push
# one or more jobs and each by default run in it's own vm-runner
jobs:
  # Job 1 and it's name
  Example-Actions-Job:
    # display name of job 1
    name: Exploring GitHub Actions
    # is a required element that defines a machine to run the job 1 on
    runs-on: ubuntu-latest
    # steps of job 1, that a sequence of tasks to be run. can be setup tasks, commands or action
    steps:
      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      
      # Runner information
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by Github"

      # Information about the repository and branch
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Use Action located in https://github.com/actions
      - name: Check out repository code
        uses: actions/checkout@v2  
        
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."
      
      - run: echo "The workflow is now ready to test your code on the runner."
      
      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Display dotnet version
        run: dotnet --version
      
      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
      
      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}
      
      - run: echo "This job's status is ${{ job.status }}."

  Second-Job:
    name: The second job running on another runner
    runs-on: windows-latest
    needs: Example-Actions-Job
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."   

        

        
      
    
    
